# Generated by Django 5.0 on 2023-12-21 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('desc', models.CharField(max_length=500)),
                ('upload_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
