# Generated by Django 5.0 on 2023-12-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Author_name',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
